    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/orchestrator`
127.0.0.1 127.0.0.1 127.0.0.1 
127
[127, 0, 0, 1]
[127, 0, 0, 1]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
HOST:  127.0.0.1
Error listening:  listen tcp 127.0.0.1:3335: bind: address already in use
exit status 1
HOST:  127.0.0.1
Error listening: listen tcp 127.0.0.1:3332: bind: address already in use
exit status 1
